// Generated by DesignToCode

import { Component } from "@angular/core";
import { BasicButton } from "../../shared/ui/basic-button/basic-button";

@Component({
  selector: "app-showcase-basic-button",
  standalone: true,
  imports: [BasicButton],
  templateUrl: "./showcase-basic-button.html",
})
export class ShowcaseBasicButton {}
