// Generated by DesignToCode

import { Component } from "@angular/core";
import { Footer } from "../../core/footer/footer";

@Component({
  selector: "app-showcase-footer",
  standalone: true,
  imports: [Footer],
  templateUrl: "./showcase-footer.html",
})
export class ShowcaseFooter {}
