// Generated by DesignToCode

import { Component } from "@angular/core";
import { Header } from "../../core/header/header";

@Component({
  selector: "app-showcase-header",
  standalone: true,
  imports: [Header],
  templateUrl: "./showcase-header.html",
})
export class ShowcaseHeader {}
