// Generated by DesignToCode

import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import { FormControl, FormGroup, ReactiveFormsModule } from "@angular/forms";
import { Dropdown, DropdownOption } from "../../shared/ui/dropdown/dropdown";

@Component({
  selector: "app-showcase-dropdown",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, Dropdown],
  templateUrl: "./showcase-dropdown.html",
})
export class ShowcaseDropdown {
  public defaultOptions: DropdownOption[] = [
    { id: 1, label: "Option 1", value: "option1" },
    { id: 2, label: "Option 2", value: "option2" },
    { id: 3, label: "Option 3", value: "option3" },
    { id: 4, label: "Option 4", value: "option4" },
  ];


  public form = new FormGroup({
    dropdown: new FormControl(null),
  });

}
