// Generated by DesignToCode

import { Component } from "@angular/core";
import { InfoMessage } from "../../features/waiting-list/info-message/info-message";

@Component({
  selector: "app-showcase-info-message",
  standalone: true,
  imports: [InfoMessage],
  templateUrl: "./showcase-info-message.html",
})
export class ShowcaseInfoMessage {}
