// Generated by DesignToCode

import { CommonModule } from '@angular/common';
import { Component, ElementRef, ViewChild, computed, input, output } from '@angular/core';
import { SvgIconComponent } from 'angular-svg-icon';

export type OutlineButtonSize = 'small' | 'medium' | 'large';
export type OutlineButtonIconPosition = 'left' | 'right';

@Component({
  selector: 'app-outline-button',
  standalone: true,
  imports: [CommonModule, SvgIconComponent],
  templateUrl: './outline-button.html',
})
export class OutlineButton {
  @ViewChild('button') public buttonRegularRef: ElementRef<HTMLElement> | null = null;
  public buttonClicked = output<boolean>();

  // Inputs
  public size = input<OutlineButtonSize>('medium');
  public label = input<string>('Button CTA');
  public icon = input<string>('arrow-left.svg');
  public iconPosition = input<OutlineButtonIconPosition>('left');
  public disabled = input<boolean>(false);

  // Computed classes
  public buttonClasses = computed(() => {
    const classes: string[] = [];

    // Always add the class group
    classes.push('group');

    // Always add the class flex
    classes.push('flex');

    // Base button styles
    classes.push(
      'rounded-[999px]',
      'flex-nowrap',
      'flex-row',
      'items-center',
      'justify-center',
      'w-fit',
    );

    // Background and border styles
    classes.push('bg-[#FCFCFD]', 'border-2', 'rounded-[999px]');

    // Size states
    if (this.size() === 'small') {
      classes.push('h-[32px]', 'pl-2', 'pr-3', 'pt-2', 'pb-2', 'gap-1');
    } else if (this.size() === 'medium') {
      classes.push('h-[40px]', 'pl-2', 'pr-3', 'pt-2', 'pb-2', 'gap-1');
    } else if (this.size() === 'large') {
      classes.push('h-[48px]', 'pl-3', 'pr-4', 'pt-4', 'pb-4', 'gap-1');
    }

    // Disabled states
    if (this.disabled()) {
      classes.push('border-[#DCE4ED]', 'hover:cursor-not-allowed');
    } else {
      // Default state
      classes.push('border-[#026E78]');
      // Hover state
      classes.push('hover:border-[#015364]', 'hover:cursor-pointer');
      // Focus state
      classes.push('focus:border-[#026E78]');
      // Active/pressed state
      classes.push('active:border-[#026E78]');
    }

    // Box shadows for non-disabled states
    if (!this.disabled()) {
      classes.push('hover:shadow-[0px_1px_2px_0px_rgba(198,228,246,0.05)]');
      classes.push('focus:shadow-[0px_0px_0px_4px_rgba(148,243,218,0.5)]');
    }

    return classes;
  });

  public iconContainerClasses = computed(() => {
    const classes: string[] = [];

    // Always add flex
    classes.push('flex', 'flex-col', 'items-center', 'justify-center', 'h-fit');

    // Size-specific icon container styles
    if (this.size() === 'small') {
      classes.push('w-[20px]', 'p-1');
    } else if (this.size() === 'medium') {
      classes.push('w-[20px]', 'p-1');
    } else if (this.size() === 'large') {
      classes.push('w-[24px]', 'pl-[5px]', 'pr-[5px]', 'pt-[5px]', 'pb-[5px]');
    }

    return classes;
  });

  public iconClasses = computed(() => {
    const classes: string[] = [];

    // Size-specific icon styles
    if (this.size() === 'small') {
      classes.push('w-[11px]', 'h-[11px]');
    } else if (this.size() === 'medium') {
      classes.push('w-[11px]', 'h-[11px]');
    } else if (this.size() === 'large') {
      classes.push('w-[14px]', 'h-[13px]');
    }

    // Disabled states
    if (this.disabled()) {
      classes.push('fill-[#838B98]');
    } else {
      // Default state
      classes.push('fill-[#026E78]');
      // Hover state
      classes.push('group-hover:fill-[#015364]');
      // Focus state
      classes.push('group-focus:fill-[#026E78]');
      // Active state
      classes.push('group-active:fill-[#026E78]');
    }

    return classes;
  });

  public textClasses = computed(() => {
    const classes: string[] = [];

    // Base text styles
    classes.push('h-fit', 'w-fit', 'font-normal', 'tracking-normal', 'text-left');

    // Size-specific text styles
    if (this.size() === 'small') {
      classes.push('text-sm', 'leading-[14px]');
    } else if (this.size() === 'medium') {
      classes.push('text-sm', 'leading-[14px]');
    } else if (this.size() === 'large') {
      classes.push('text-base', 'leading-4');
    }

    // Disabled states
    if (this.disabled()) {
      classes.push('text-[#838B98]');
    } else {
      // Default state
      classes.push('text-[#026E78]');
      // Hover state
      classes.push('group-hover:text-[#015364]');
      // Focus state
      classes.push('group-focus:text-[#026E78]');
      // Active state
      classes.push('group-active:text-[#026E78]');
    }

    return classes;
  });

  /**
   * Emits the click
   *
   */
  public submit(): void {
    if (!this.disabled()) {
      this.buttonRegularRef?.nativeElement.blur();
      this.buttonClicked.emit(true);
    }
  }
}
