// Generated by DesignToCode

import { CommonModule } from '@angular/common';
import { Component, input } from '@angular/core';
import { BasicButton, BasicButtonSize } from '../../shared/ui/basic-button/basic-button';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, BasicButton],
  templateUrl: './footer.html',
})
export class Footer {
  // Inputs
  public termsAndConditionsText = input<string>('Terms and Conditions');
  public privacyPolicyText = input<string>('Privacy Policy');
  public buttonSize = input<BasicButtonSize>('small');
  public buttonLabel = input<string>('Contact');

  // Outputs
}
