// Generated by DesignToCode

import { Component } from "@angular/core";
import { OutlineButton } from "../../shared/ui/outline-button/outline-button";

@Component({
  selector: "app-showcase-outline-button",
  standalone: true,
  imports: [OutlineButton],
  templateUrl: "./showcase-outline-button.html",
})
export class ShowcaseOutlineButton {}
