// Generated by DesignToCode

import { Component } from "@angular/core";
import { Form } from "../../features/waiting-list/form/form";

@Component({
  selector: "app-showcase-form",
  standalone: true,
  imports: [Form],
  templateUrl: "./showcase-form.html",
})
export class ShowcaseForm {
}
