// Generated by DesignToCode

import { CommonModule } from '@angular/common';
import { Component, ElementRef, ViewChild, computed, input, output } from '@angular/core';

export type BasicButtonSize = 'small' | 'medium' | 'large';

@Component({
  selector: 'app-basic-button',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './basic-button.html',
})
export class BasicButton {
  @ViewChild('button') public buttonRegularRef: ElementRef<HTMLElement> | null = null;
  public buttonClicked = output<boolean>();

  // Inputs
  public size = input<BasicButtonSize>('medium');
  public label = input<string>('');
  public disabled = input<boolean>(false);

  // Computed classes for the button element
  public buttonClasses = computed(() => {
    const classes: string[] = [];

    classes.push(
      'group',
      'flex',
      'pl-0',
      'pr-0',
      'pt-0',
      'pb-0',
      'rounded-[999px]',
      'flex-nowrap',
      'flex-row',
      'items-start',
      'justify-start',
      'w-fit',
    );

    // Size-specific height
    if (this.size() === 'small') {
      classes.push('h-[36px]');
    } else if (this.size() === 'medium') {
      classes.push('h-[40px]');
    } else if (this.size() === 'large') {
      classes.push('h-[48px]');
    }

    // Cursor handling
    if (this.disabled()) {
      classes.push('hover:cursor-not-allowed');
    } else {
      classes.push('hover:cursor-pointer');
    }

    return classes;
  });

  // Computed classes for the button core (inner div)
  public buttonCoreClasses = computed(() => {
    const classes: string[] = [];

    classes.push(
      'flex',
      'pl-4',
      'pr-4',
      'rounded-[999px]',
      'flex-nowrap',
      'flex-row',
      'items-center',
      'justify-center',
      'w-fit',
      'gap-2',
    );

    // Size-specific padding and height
    if (this.size() === 'small') {
      classes.push('pt-2', 'pb-2', 'h-full');
    } else if (this.size() === 'medium') {
      classes.push('pt-2', 'pb-2', 'h-[40px]');
    } else if (this.size() === 'large') {
      classes.push('pt-2', 'pb-2', 'h-full');
    }

    // Default state styles
    if (this.disabled()) {
      // Disabled state
      classes.push('bg-[#DCE4ED]', 'border', 'border-[#DCE4ED]');
    } else {
      // Default state
      classes.push('bg-[#026E78]', 'border', 'border-[#026E78]');
      // Hover state
      classes.push('group-hover:bg-[#015364]', 'group-hover:border-[#015364]');
      // Focus state
      classes.push('group-focus:bg-[#94F3DA]', 'group-focus:border-transparent');
    }

    return classes;
  });

  // Computed classes for the label
  public labelClasses = computed(() => {
    const classes: string[] = [];

    classes.push(
      'flex',
      'pl-0',
      'pr-0',
      'pt-0',
      'pb-0',
      'flex-wrap',
      'flex-row',
      'items-start',
      'justify-start',
      'h-fit',
      'w-fit',
      'font-normal',
      'tracking-normal',
      'text-left',
    );

    // Size-specific font styles
    if (this.size() === 'small') {
      classes.push('text-sm', 'leading-[14px]');
    } else if (this.size() === 'medium') {
      classes.push('text-sm', 'leading-[14px]');
    } else if (this.size() === 'large') {
      classes.push('text-base', 'leading-4');
    }

    // State-specific text color
    if (this.disabled()) {
      classes.push('text-[#454A54]');
    } else {
      // Default and hover state
      classes.push('text-[#FCFCFD]');
      // Focus state
      classes.push('group-focus:text-[#454A54]');
    }

    return classes;
  });

  /**
   * Emits the click
   */
  public submit(): void {
    if (!this.disabled()) {
      this.buttonRegularRef?.nativeElement.blur();
      this.buttonClicked.emit(true);
    }
  }
}
