// Generated by DesignToCode

import { CommonModule } from '@angular/common';
import {
  Component,
  ElementRef,
  OnDestroy,
  OnInit,
  ViewChild,
  computed,
  effect,
  input,
  signal,
} from '@angular/core';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { Subject, takeUntil } from 'rxjs';

export type IntermidiateInputType = 'text';
export type IntermidiateInputSize = 'default';

@Component({
  selector: 'app-intermidiate-input',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './intermidiate-input.html',
})
export class IntermidiateInput implements OnInit, OnDestroy {
  @ViewChild('inputContainer', { static: true }) inputContainerRef!: ElementRef;

  // Inputs
  public formGroup = input.required<FormGroup>();
  public controlName = input.required<string>();
  public label = input<string>('');
  public readonly = input<boolean>(false);
  public showValidationTemplates = input<boolean>(false);
  public placeholder = input<string>('');
  public disabled = input<boolean>(false);
  public helpText = input<string>('');
  public type = input<IntermidiateInputType>('text');
  public size = input<IntermidiateInputSize>('default');
  public hasHelpText = input<boolean>(true);

  // States
  private isHovered = signal(false);
  private isFilling = signal(false);
  private isFocused = signal(false);
  private isFilled = signal(false);

  private destroy$ = new Subject<void>();

  private formState = signal({
    invalid: false,
    dirty: false,
    touched: false,
    valid: false,
  });

  constructor() {
    effect(() => {
      const fc = this.formGroup()?.get(this.controlName());
      if (fc?.value != null && fc?.value !== '') {
        this.isFilled.set(true);
      }
    });
  }

  ngOnInit(): void {
    if (this.control() != null) {
      this.control()
        .statusChanges.pipe(takeUntil(this.destroy$))
        .subscribe(() => {
          if (
            this.formState().dirty !== this.control().dirty ||
            this.formState().invalid !== this.control().invalid ||
            this.formState().touched !== this.control().touched ||
            this.formState().valid !== this.control().valid
          ) {
            this.formState.set({
              invalid: this.control().invalid,
              dirty: this.control().dirty,
              touched: this.control().touched,
              valid: this.control().valid,
            });
          }
        });

      this.control()
        .valueChanges.pipe(takeUntil(this.destroy$))
        .subscribe((value) => {
          this.isFocused.set(false);
          this.isFilling.set(true);
        });
    }
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  public control = computed(() => {
    const fc = this.formGroup()?.get(this.controlName());
    return fc as FormControl;
  });

  public onMouseEnter() {
    this.isHovered.set(true);
  }

  public onMouseLeave() {
    this.isHovered.set(false);
  }

  public onFocus() {
    this.isFocused.set(true);
    this.isFilled.set(false);
  }

  public onBlur() {
    this.isFocused.set(false);
    this.isFilling.set(false);
    this.isFilled.set(this.control().value != null && this.control().value !== '');
    this.formState.set({
      invalid: this.control().invalid,
      dirty: this.control().dirty,
      touched: this.control().touched,
      valid: this.control().valid,
    });
  }

  public tabIndexInput = computed(() => {
    return this.disabled() || this.readonly() ? -1 : 0;
  });

  public containerClasses = computed(() => {
    const classes: string[] = [
      'flex',
      'flex-col',
      'flex-nowrap',
      'items-start',
      'justify-center',
      'pl-2',
      'pr-2',
      'pt-2',
      'pb-2',
      'rounded',
      'border',
      'h-fit',
      'w-full',
      'gap-2.5',
      'bg-[#FCFCFD]',
    ];

    if (this.hasError()) {
      classes.push('border-[#CD0063]');
    } else if (this.isSuccess()) {
      classes.push('border-[#02785C]');
    } else {
      if (this.isFilling() && !this.disabled()) {
        classes.push('border-[#0096CD]', 'shadow-[0px_0px_0px_2px_rgba(0,150,205,0.1)]');
      } else if (this.isFocused() && !this.disabled()) {
        classes.push('border-[#0096CD]', 'shadow-[0px_0px_0px_2px_rgba(0,150,205,0.1)]');
      } else if (this.isHovered() && !this.disabled()) {
        classes.push('border-[#015364]');
      } else if (this.isFilled() && !this.disabled()) {
        classes.push('border-[#454A54]');
      } else if (this.disabled()) {
        classes.push('border-[#DCE4ED]');
      } else {
        classes.push('border-[#454A54]');
      }
    }

    return classes.join(' ');
  });

  public inputClasses = computed(() => {
    const classes: string[] = [
      'flex',
      'flex-wrap',
      'flex-row',
      'items-start',
      'justify-start',
      'pl-0',
      'pr-0',
      'pt-0',
      'pb-0',
      'h-fit',
      'w-full',
      'bg-transparent',
      'border-0',
      'outline-none',
      'font-normal',
      'text-sm',
      'leading-5',
      'tracking-normal',
      'text-left',
    ];

    if (this.hasError()) {
      classes.push('text-[#CD0063]', 'placeholder:text-[#454A54]');
    } else if (this.isSuccess()) {
      classes.push('text-[#02785C]', 'placeholder:text-[#454A54]');
    } else {
      if (this.isFilling() && !this.disabled()) {
        classes.push('text-[#454A54]', 'placeholder:text-[#454A54]');
      } else if (this.isFocused() && !this.disabled()) {
        classes.push('text-[#454A54]', 'placeholder:text-[#454A54]');
      } else if (this.isHovered() && !this.disabled()) {
        classes.push('text-[#454A54]', 'placeholder:text-[#454A54]');
      } else if (this.isFilled() && !this.disabled()) {
        classes.push('text-[#454A54]', 'placeholder:text-[#454A54]');
      } else if (this.disabled()) {
        classes.push('text-[#838B98]', 'placeholder:text-[#838B98]');
      } else {
        classes.push('text-[#454A54]', 'placeholder:text-[#454A54]');
      }
    }

    return classes.join(' ');
  });

  public hasError = computed(() => {
    const state = this.formState();
    return (
      (state.invalid &&
        state.dirty &&
        state.touched &&
        this.showValidationTemplates() &&
        !this.isFilling()) ||
      false
    );
  });

  public isSuccess = computed(() => {
    const state = this.formState();
    return (
      (state.valid && state.dirty && this.showValidationTemplates() && !this.isFilling()) || false
    );
  });

  public messageClasses = computed(() => {
    const classes: string[] = [];
    return classes.join(' ');
  });

  public labelClasses = computed(() => {
    const classes: string[] = [
      'flex',
      'flex-wrap',
      'flex-row',
      'items-start',
      'justify-start',
      'pl-0',
      'pr-0',
      'pt-0',
      'pb-0',
      'h-fit',
      'w-full',
      'font-semibold',
      'text-sm',
      'leading-4',
      'tracking-normal',
      'text-left',
    ];

    if (this.hasError()) {
      classes.push('text-[#454A54]');
    } else if (this.isSuccess()) {
      classes.push('text-[#454A54]');
    } else if (this.disabled()) {
      classes.push('text-[#454A54]');
    } else {
      classes.push('text-[#454A54]');
    }

    return classes.join(' ');
  });

  public helpTextClasses = computed(() => {
    const classes: string[] = [
      'flex',
      'flex-wrap',
      'flex-row',
      'items-start',
      'justify-start',
      'pl-0',
      'pr-0',
      'pt-0',
      'pb-0',
      'h-fit',
      'w-full',
      'font-normal',
      'text-xs',
      'leading-4',
      'tracking-normal',
      'text-left',
    ];

    if (this.hasError()) {
      classes.push('text-[#CD0063]');
    } else if (this.isSuccess()) {
      classes.push('text-[#02785C]');
    } else if (this.disabled()) {
      classes.push('text-[#454A54]');
    } else {
      classes.push('text-[#454A54]');
    }

    return classes.join(' ');
  });
}
