// Generated by DesignToCode

import { CommonModule } from '@angular/common';
import { Component, input } from '@angular/core';
import { BasicButton, BasicButtonSize } from '../../shared/ui/basic-button/basic-button';
import { OutlineButton, OutlineButtonSize } from '../../shared/ui/outline-button/outline-button';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, OutlineButton, BasicButton],
  templateUrl: './header.html',
})
export class Header {
  // Inputs
  public logoUrl = input<string>('logo.svg');
  public avatarUrl = input<string>('avatar.svg');
  public backButtonLabel = input<string>('Back to Dashboard');
  public mainMenuButtonLabel = input<string>('Main Menu');
  public outlineButtonSize = input<OutlineButtonSize>('small');
  public basicButtonSize = input<BasicButtonSize>('small');
}
