// Generated by DesignToCode

import { CommonModule } from "@angular/common";
import { Component, input } from "@angular/core";
import { SvgIconComponent } from "angular-svg-icon";
import { BasicButton, BasicButtonSize } from "../../../shared/ui/basic-button/basic-button";

@Component({
  selector: "app-info-message",
  standalone: true,
  imports: [CommonModule, SvgIconComponent, BasicButton],
  templateUrl: "./info-message.html",
})
export class InfoMessage {
  // Inputs
  public title = input<string>("Title Text");
  public content = input<string>(
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
  );
  public hasAction = input<boolean>(true);
  public buttonLabel = input<string>("Confirm");
  public buttonSize = input<BasicButtonSize>("small");

  // Outputs
}
