// Generated by DesignToCode

import { CommonModule } from '@angular/common';
import { Component, input, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { BasicButton, BasicButtonSize } from '../../../shared/ui/basic-button/basic-button';
import {
  IntermidiateInput,
  IntermidiateInputSize,
  IntermidiateInputType,
} from '../../../shared/ui/intermidiate-input/intermidiate-input';

@Component({
  selector: 'app-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, BasicButton, IntermidiateInput],
  templateUrl: './form.html',
})
export class Form {
  // Signals for typed inputs
  public title = signal<string>('Join the Waitlist');
  public subtitle = signal<string>('Be the first to know when we launch');
  public fullNameLabel = signal<string>('Full Name');
  public emailLabel = signal<string>('Email Address');
  public buttonLabel = signal<string>('Join Waitlist');
  public buttonSize = signal<BasicButtonSize>('small');
  public inputType = signal<IntermidiateInputType>('text');
  public inputSize = signal<IntermidiateInputSize>('default');

  public formGroup = signal<FormGroup>(
    new FormGroup({
      fullName: new FormControl(''),
      email: new FormControl(''),
    }),
  );
}
