// Generated by DesignToCode

import { Component } from "@angular/core";
import { FormControl, FormGroup, Validators } from "@angular/forms";
import { IntermidiateInput } from "../../shared/ui/intermidiate-input/intermidiate-input";

@Component({
  selector: "app-showcase-intermidiate-input",
  standalone: true,
  imports: [IntermidiateInput],
  templateUrl: "./showcase-intermidiate-input.html",
})
export class ShowcaseIntermidiateInput {
  formGroup1 = new FormGroup({
    basicInput: new FormControl(""),
  });

  formGroup2 = new FormGroup({
    helpTextInput: new FormControl(""),
  });

  formGroup3 = new FormGroup({
    noHelpTextInput: new FormControl(""),
  });

  formGroup4 = new FormGroup({
    disabledInput: new FormControl({ value: "Disabled value", disabled: true }),
  });

  formGroup5 = new FormGroup({
    readonlyInput: new FormControl("Readonly value"),
  });

  formGroup6 = new FormGroup({
    validationInput: new FormControl("", [Validators.required]),
  });
}
